const _weeks = [
    { "id": 0, "weekNum": 1, "weeklyPicture": require("../assets/day1.jpg"), "weight": 1540, "length": 39 },
    { "id": 1, "weekNum": 2, "weeklyPicture": require("../assets/day8.jpg"), "weight": 1350, "length": 39 },
    { "id": 2, "weekNum": 3, "weeklyPicture": require("../assets/day15.jpg"), "weight": 1580, "length": 39 },
    { "id": 3, "weekNum": 4, "weeklyPicture": require("../assets/day22.jpg"), "weight": 1695, "length": 39 }
]
const _dailyUpdates = [
    { "id": 0, "weekId": 0, "date": "6/19/2021", "details": "Born Today! It's cold out here!", "weight": 1540, "additionalDetails": "Luke was born after complications due to pre-eclampsia. Kelly's Liver was secreting proteins showing it was starting to fail, so the doctors induced labor for vaginal delivery. Luke then switch between breach and transverse positions, and so the doctors advised a c-section while Luke's levels were strong. And so we had our baby boy early at 33 weeks, 4 days gestation.", "dailyPicture": require("../assets/day1.jpg")},
    { "id": 1, "weekId": 0, "date": "6/20/2021", "details": "My nose air is less, and I'm doing great!", "weight": 1200, "additionalDetails": "Luke required a CPAP at first to help his lungs remain open while they absorbed the amniotic fluid and expanded their tiny air sacs. He was on room oxygen from the start, which is a great sign.", "dailyPicture": require("../assets/day2.jpg")},
    { "id": 2, "weekId": 0, "date": "6/21/2021", "details": "Big nose thingy gone, just tiny hose now.", "weight": 1240, "additionalDetails": "Luke's lungs are strong! He was able to get off his CPAP completely, and is now on a high-flow nose cannula at 4 litres.", "dailyPicture": require("../assets/day3.jpg")},
    { "id": 3, "weekId": 0, "date": "6/22/2021", "details": "Tiny nose hose is reduced, shiny light is annoying", "weight": 1230, "additionalDetails": "Luke's bilirubin levels were elevated, and so he needed some photo therapy to combat jaundice. His levels weren't alarmingly high, the doctors are just being cautious due to his premature status.", "dailyPicture": require("../assets/day4.jpg")},
    { "id": 4, "weekId": 0, "date": "6/23/2021", "details": "Big blue light today, Mommy was able to leave the hospital, AND no more tiny nose hose!", "weight": 1250, "additionalDetails": "Luke was able to get off of the high-flow nose cannula today since he was keeping his O2 saturation during his weaning process. His bilirubin levels are getting better, but he still requires a little more phototherapy for now. Luke also got something called an infiltration today, where his pick line IV caused his vein to blow. His nurse recognized it within moments of it happening, and was able to take the necessary steps to help save him. We're so grateful for these wonderful NICU nurses!", "dailyPicture": require("../assets/day5.jpg")},
    { "id": 5, "weekId": 0, "date": "6/24/2021", "details": "No more sticky needles! Just milk now!", "weight": 1280, "additionalDetails": "The doctors were able to remove his new IV, and now he just needs milk through his NG tube! Our little man is getting so strong, it gives us hope!", "dailyPicture": require("../assets/day6.jpg")},
    { "id": 6, "weekId": 0, "date": "6/25/2021", "details": "I graduated to level 2 today for healthy babies!", "weight": 1320, "additionalDetails": "Today we were told that Luke is doing so well that he \"Graduated\" to Level 2, which is a group of babies that are considered super-healthy! We're so proud of our little man!", "dailyPicture": require("../assets/day7.jpg")},
    { "id": 7, "weekId": 1, "date": "6/26/2021", "details": "No more risk of jaundice, and Daddy helped Mommy give me a bed bath!", "weight": 1350, "additionalDetails": "We were able to give Luke his first bath today! Kelly worked with him to breastfeed, but he wasn't feeling it. And his bilirubin levels are now self-resolving, so he no longer needs phototherapy!", "dailyPicture": require("../assets/day8.jpg")},
    { "id": 8, "weekId": 1, "date": "6/27/2021", "details": "Latched onto Mommy today! And am now back into the 3 pound range!", "weight": 1400, "additionalDetails": "His care plan is simply let him rest and eat and grow. He had a couple of stat dips while doing skin-to-skin, but that was just how he was held. Little guy is doing great.", "dailyPicture": require("../assets/day9.jpg") },
    { "id": 9, "weekId": 1, "date": "6/28/2021", "details": "Flew to a new hostpital today, and they did a kitty scan on me. Kinda groggy today, but still doing good.", "weight": 1535, "additionalDetails": "Transferred to Primary Childrens today after the NICU nurse noticed the redness on his neck that we pointed out started expanding. CT Scan at Primary Children's helped them to identify it as Cellulitis, and he's on antibiotics to treat that now. We will most likely do more tests to find out what the mass underneath the infection is, and how we will handle it.", "dailyPicture": require("../assets/day10.jpg") },
    { "id": 10, "weekId": 1, "date": "6/29/2021", "details": "Had to get intubated today cause my neck was swollen with infection. I made it through everything okay, and they're draining my owie in my neck.", "weight": 1535, "additionalDetails": "Luke had to get intubated in the OR because his airway was collapsing. They were able to intubate, and then the Interventive Radiology team drained his abscess, and put a shunt in to allow it to finish draining over the next few days. He'll be intubated until they take the shunt out.", "dailyPicture": require("../assets/day11.jpg") },
    { "id": 11, "weekId": 1, "date": "6/30/2021", "details": "Doctors found MRSA in the juice from my owie. They already are giving me meds for it though, so I'll be OK!!", "weight":1535, "additionalDetails": "The doctors found MRSA in the pus that was drained from Luke's abscess. It's very treatable with the antibiotic they already had him on. We do not know how he got the infection, and they're looking into it.", "dailyPicture": require("../assets/day12.jpg") },
    { "id": 12, "weekId": 1, "date": "7/1/2021", "details": "I am eating more food, and took my first poop at this new NICU! Daddy also gave me a hand hug, for the first time in days!", "weight": 1510, "additionalDetails": "Luke is pooping again, and they're increasing his feed, which should help a lot with his weight gain. His MRSA meds were changed to fight his particular strain more effectively, and once he's healed up he is no longer contagious!", "dailyPicture": require("../assets/day13.jpg") },
    { "id": 13, "weekId": 1, "date": "7/2/2021", "details": "Doctors say I get my drain tube out of my owie tomorrow! Daddy got to hold me for the first time since I came to the new NICU!", "weight": 1510, "additionalDetails": "Luke's progress is great, and there hasn't been any new fluid to drain the last 24 hours from his abscess. Doctors will remove the drain tomorrow, and as long as no flare-ups occur, he'll be extubated the following day! Also, the Disease Team Doctors stopped by to say that when we take Luke home, he's not going to be contagious, and that no extra precautions are needed!!!", "dailyPicture": require("../assets/day14.jpg") },
    { "id": 14, "weekId": 2, "date": "7/3/2021", "details": "I got my drain tube out today! I feel sooo much better without it! And I weigh more than the day I was born!", "weight": 1580, "additionalDetails": "Luke's drainage tube required some assistance from the Interventive Radiology doctors to remove since it was a newer drain type. He's doing much better, and his pain levels are much more manageable.", "dailyPicture": require("../assets/day15.jpg") },
    { "id": 15, "weekId": 2, "date": "7/4/2021", "details": "Happy Birthday Mommy!! The Doctors \"Extubed\" me today, and now I have a belly button!! Happy 4th of July everyone!", "weight": 1590, "additionalDetails": "Luke got extubated today, which was wonderful because now our little man is breathing without the ventilator. His umbilical cord fell off, so now he has the CUTEST belly button! We're so happy that he's no longer hooked up to those machines, although he does have a nasal cannula just until he is used to being off the ventilator.", "dailyPicture": require("../assets/day16.jpg") },
    { "id": 16, "weekId": 2, "date": "7/5/2021", "details": "I'm doing really good, but have tiny nose tube again while I recover from everything still.", "weight": 1600, "additionalDetails": "Luke has a nasal cannula while he recovers from being on ventilation. He is taking all his medications orally now, and so tomorrow we'll be removing his leg IV!! He also has been doing great maintaining body temperature, so a crib is coming up soon!!", "dailyPicture": require("../assets/day17.jpg") },
    { "id": 17, "weekId": 2, "date": "7/6/2021", "details": "Today I wore my first preemie outfits! I also got to be held skin-to-skin with Mommy, and the ENT doctors said my neck looked great!", "weight": 1610, "additionalDetails": "Luke still has some difficulty breathing while he recovers from his intubation, but he's still doing great. The nurses are going to take out his Extended Dwell IV tonight at midnight as long as he tolerates his full feeds.", "dailyPicture": require("../assets/day18.jpg") },
    { "id": 18, "weekId": 2, "date": "7/7/2021", "details": "I got a new bed today! And no more sticky needles to help feed me, I'm back on the bottle for all my food needs! High Five!!!", "weight": 1590, "additionalDetails": "Luke got his Extended Dwell IV removed today, and he also was moved to a crib since he's maintaining his own body temperature now! The doctors are also starting him on a regiment to get him bottle feeding so that he can eventually get off his NG Tube!", "dailyPicture": require("../assets/day19.jpg") },
    { "id": 19, "weekId": 2, "date": "7/8/2021", "details": "Today was a semi-scary day when the nurse felt a lump on my throat. They had a guy do an scan of my neck, and it turned out to be nothing! Phew!!!", "weight": 1610, "additionalDetails": "Luke was more alert and awake than any other day so far in his little life! He did have a lump on his throat, and after an ultrasound, the radiologist determined it was nothing at all, and that we didn't need to worry. He's doing good, and slowly re-gaining his weight back.", "dailyPicture": require("../assets/day20.jpg") },
    { "id": 20, "weekId": 2, "date": "7/9/2021", "details": "My little lump is gone from yesterday completely, so no worries at all! I'm also doing much better and staying awake when Mommy and Daddy visit!", "weight": 1620, "additionalDetails": "Luke is doing really well with his alertness, and is almost completely recovered from his abscess surgery. The doctor's say he is no longer in need of his pain meds, and the focus is completely on his growth and switching to bottle-feeding.", "dailyPicture": require("../assets/day21.jpg") },
    { "id": 21, "weekId": 3, "date": "7/10/2021", "details": "I got a toy today! I love it soooo much!!! I'm also almost off of my nose tube again!!!!", "weight": 1695, "additionalDetails": "Luke has been gaining a lot of weight, and is doing good. The focus now is him resting, growing, and learning how to bottlefeed. We are also happy that he is on 1/8th of a litre of air now!", "dailyPicture": require("../assets/day22.jpg") },
    { "id": 22, "weekId": 3, "date": "7/11/2021", "details": "Doctors say I just need to sleep and grow!! So today I rested on Mommy while Daddy read me some stories.", "weight": 1730, "additionalDetails": "Luke's recovery and health are doing great! He is so much more alert and active during our visits, it warms our hearts so much. We are hopeful he'll be home before his due date!", "dailyPicture": require("../assets/day23.jpg") },
    { "id": 23, "weekId": 3, "date": "7/12/2021", "details": "Today I did a video call with my brother Trison while Daddy held me. I'm also doing really well gaining my weight, and am almost 4 pounds!", "weight": 1780, "additionalDetails": "Luke is still on his nasal cannula with a very low-flow. We spoke to his Nurse Practitioner, and they're going to do a trial \"Room Air Only\" tomorrow to see if they can just remove his nasal cannula for good!", "dailyPicture": require("../assets/day24.jpg") },
    { "id": 24, "weekId": 3, "date": "7/13/2021", "details": "I finished my medicine for my MRSA today, and the doctors say my blood tests showed no signs of infection!!! They also scanned my brain, and it looks normal too!", "weight": 1795, "additionalDetails": "Luke is officially full term (37 weeks gestation) today! He had some reflux that lead to him having a Bradycardia event that worried us because of the last one he had. But the nurses and doctors are sure it's just reflux. They are going to monitor him closely though to ensure no other Bradys(Bradycardia Events) occur. He is also off of his antibiotics, and is no longer showing signs of infection! And finally, the doctors did an ultrasound of his brain to make sure it looked as they expected now that he's full term -- and it looked great!", "dailyPicture": require("../assets/day25.jpg")}
]
const _family = [
    { "id": 0, "name": "Curt Houghton", "relation": "Daddy", "birthDate": "10/28/1988", "birthWeight": 4365, "birthLength": 48.3, "photo": require("../assets/daddy.jpg") },
    { "id": 1, "name": "Kelly Houghton", "relation": "Mommy", "birthDate": "7/4/1984", "birthWeight": 2381, "birthLength": 48.3, "photo": require("../assets/mommy.jpg") },
    { "id": 2, "name": "Trey Parks", "relation": "Brother", "birthDate": "4/12/2010", "birthWeight": 4422, "birthLength": 54.6, "photo": require("../assets/day3.jpg") },
    { "id": 3, "name": "Trison Gardner", "relation": "Brother", "birthDate": "8/16/2010", "birthWeight": 3713, "birthLength": 50.8, "photo": require("../assets/day4.jpg") },
    { "id": 4, "name": "Peiper Tomlinson", "relation": "Sister", "birthDate": "11/9/2014", "birthWeight": 3713, "birthLength": 53.3, "photo": require("../assets/day5.jpg") }
]

export default {
    getWeeks(cb) {
        setTimeout(() => cb(_weeks), 100);
    },
    getDailyUpdates(cb) {
        setTimeout(() => cb(_dailyUpdates), 100);
    },
    getFamily(cb) {
        setTimeout(() => cb(_family), 100);
    }
}