const _weeks = [
    { "id": 0, "weekNum": 1, "weeklyPicture": require("../assets/day1.jpg"), "weight": 1540, "length": 39 },
    { "id": 1, "weekNum": 2, "weeklyPicture": require("../assets/day8.jpg"), "weight": 1350, "length": 39 },
    { "id": 2, "weekNum": 3, "weeklyPicture": require("../assets/day15.jpg"), "weight": 1580, "length": 39 }
]
const _dailyUpdates = [
    { "id": 0, "weekId": 0, "date": "6/19/2021", "details": "Born Today! It's cold out here!", "weight": 1540, "additionalDetails": "Luke was born after complications due to pre-eclampsia.", "dailyPicture": require("../assets/day1.jpg")},
    { "id": 1, "weekId": 0, "date": "6/20/2021", "details": "My nose air is less, and I'm doing great!", "weight": 1200, "additionalDetails": "Luke was born after complications due to pre-eclampsia.", "dailyPicture": require("../assets/day2.jpg")},
    { "id": 2, "weekId": 0, "date": "6/21/2021", "details": "Big nose thingy gone, just tiny hose now.", "weight": 1240, "additionalDetails": "Luke was born after complications due to pre-eclampsia.", "dailyPicture": require("../assets/day3.jpg")},
    { "id": 3, "weekId": 0, "date": "6/22/2021", "details": "Tiny nose hose is reduced, shiny light is annoying", "weight": 1230, "additionalDetails": "Luke was born after complications due to pre-eclampsia.", "dailyPicture": require("../assets/day4.jpg")},
    { "id": 4, "weekId": 0, "date": "6/23/2021", "details": "Big blue light today, Mommy was able to leave the hospital, AND no more tiny nose hose!", "weight": 1250, "additionalDetails": "Luke was born after complications due to pre-eclampsia.", "dailyPicture": require("../assets/day5.jpg")},
    { "id": 5, "weekId": 0, "date": "6/24/2021", "details": "No more sticky needles! Just milk now!", "weight": 1280, "additionalDetails": "Luke was born after complications due to pre-eclampsia.", "dailyPicture": require("../assets/day6.jpg")},
    { "id": 6, "weekId": 0, "date": "6/25/2021", "details": "I graduated to level 2 today for healthy babies!", "weight": 1320, "additionalDetails": "Luke was born after complications due to pre-eclampsia.", "dailyPicture": require("../assets/day7.jpg")},
    { "id": 7, "weekId": 1, "date": "6/26/2021", "details": "No more risk of jaundice, and Daddy helped Mommy give me a bed bath!", "weight": 1350, "additionalDetails": "We were able to give Luke his first bath today! Kelly worked with him to breastfeed, but he wasn't feeling it.", "dailyPicture": require("../assets/day8.jpg")},
    { "id": 8, "weekId": 1, "date": "6/27/2021", "details": "Latched onto Mommy today! And am now back into the 3 pound range!", "weight": 1400, "additionalDetails": "His care plan is simply let him rest and eat and grow. He had a couple of stat dips while doing skin-to-skin, but that was just how he was held. Little guy is doing great.", "dailyPicture": require("../assets/day9.jpg") },
    { "id": 9, "weekId": 1, "date": "6/28/2021", "details": "Flew to a new hostpital today, and they did a kitty scan on me. Kinda groggy today, but still doing good.", "weight": 1535, "additionalDetails": "Transferred to Primary Childrens today after the NICU nurse noticed the redness on his neck that we pointed out started expanding. CT Scan at Primary Children's helped them to identify it as Cellulitis, and he's on antibiotics to treat that now. We will most likely do more tests to find out what the mass underneath the infection is, and how we will handle it.", "dailyPicture": require("../assets/day10.jpg") },
    { "id": 10, "weekId": 1, "date": "6/29/2021", "details": "Had to get intubated today cause my neck was swollen with infection. I made it through everything okay, and they're draining my owie in my neck.", "weight": 1535, "additionalDetails": "Luke had to get intubated in the OR because his airway was collapsing. They were able to intubate, and then the Interventive Radiology team drained his abscess, and put a shunt in to allow it to finish draining over the next few days. He'll be intubated until they take the shunt out.", "dailyPicture": require("../assets/day11.jpg") },
    { "id": 11, "weekId": 1, "date": "6/30/2021", "details": "Doctors found MRSA in the juice from my owie. They already are giving me meds for it though, so I'll be OK!!", "weight":1535, "additionalDetails": "The doctors found MRSA in the pus that was drained from Luke's abscess. It's very treatable with the antibiotic they already had him on. We do not know how he got the infection, and they're looking into it.", "dailyPicture": require("../assets/day12.jpg") },
    { "id": 12, "weekId": 1, "date": "7/1/2021", "details": "I am eating more food, and took my first poop at this new NICU! Daddy also gave me a hand hug, for the first time in days!", "weight": 1510, "additionalDetails": "Luke is pooping again, and they're increasing his feed, which should help a lot with his weight gain. His MRSA meds were changed to fight his particular strain more effectively, and once he's healed up he is no longer contagious!", "dailyPicture": require("../assets/day13.jpg") },
    { "id": 13, "weekId": 1, "date": "7/2/2021", "details": "Doctors say I get my drain tube out of my owie tomorrow! Daddy got to hold me for the first time since I came to the new NICU!", "weight": 1510, "additionalDetails": "Luke's progress is great, and there hasn't been any new fluid to drain the last 24 hours from his abscess. Doctors will remove the drain tomorrow, and as long as no flare-ups occur, he'll be extubated the following day! Also, the Disease Team Doctors stopped by to say that when we take Luke home, he's not going to be contagious, and that no extra precautions are needed!!!", "dailyPicture": require("../assets/day14.jpg") },
    { "id": 14, "weekId": 2, "date": "7/3/2021", "details": "I got my drain tube out today! I feel sooo much better without it! And I weigh more than the day I was born!", "weight": 1580, "additionalDetails": "Luke's drainage tube required some assistance from the Interventive Radiology doctors to remove since it was a newer drain type. He's doing much better, and his pain levels are much more manageable.", "dailyPicture": require("../assets/day15.jpg") },
    { "id": 15, "weekId": 2, "date": "7/4/2021", "details": "Happy Birthday Mommy!! The Doctors \"Extubed\" me today, and now I have a belly button!! Happy 4th of July everyone!", "weight": 1590, "additionalDetails": "Luke got extubated today, which was wonderful because now our little man is breathing without the ventilator. His umbilical cord fell off, so now he has the CUTEST belly button! We're so happy that he's no longer hooked up to those machines, although he does have a nasal cannula just until he is used to being off the ventilator.", "dailyPicture": require("../assets/day16.jpg") },
    { "id": 16, "weekId": 2, "date": "7/5/2021", "details": "I'm doing really good, but have tiny nose tube again while I recover from everything still.", "weight": 1600, "additionalDetails": "Luke has a nasal cannula while he recovers from being on ventilation. He is taking all his medications orally now, and so tomorrow we'll be removing his leg IV!! He also has been doing great maintaining body temperature, so a crib is coming up soon!!", "dailyPicture": require("../assets/day17.jpg") },
    { "id": 17, "weekId": 2, "date": "7/6/2021", "details": "Today I wore my first preemie outfits! I also got to be held skin-to-skin with Mommy, and the ENT doctors said my neck looked great!", "weight": 1610, "additionalDetails": "Luke still has some difficulty breathing while he recovers from his intubation, but he's still doing great. The nurses are going to take out his Extended Dwell IV tonight at midnight as long as he tolerates his full feeds.", "dailyPicture": require("../assets/day18.jpg") },
    { "id": 18, "weekId": 2, "date": "7/7/2021", "details": "I got a new bed today! And no more sticky needles to help feed me, I'm back on the bottle for all my food needs! High Five!!!", "weight": 1590, "additionalDetails": "Luke got his Extended Dwell IV removed today, and he also was moved to a crib since he's maintaining his own body temperature now! The doctors are also starting him on a regiment to get him bottle feeding so that he can eventually get off his NG Tube!", "dailyPicture": require("../assets/day19.jpg") }
]

export default {
    getWeeks(cb) {
        setTimeout(() => cb(_weeks), 100);
    },
    getDailyUpdates(cb) {
        setTimeout(() => cb(_dailyUpdates), 100);
    }
}